const CHANGE_THEME = 'CHANGE_THEME';
const SEARCH = 'SEARCH';
const SHOW_MODAL_ADD = 'SHOW_MODAL_ADD';
const ADD = 'ADD';
const CLOSE_MODAL_ADD = 'CLOSE_MODAL_ADD';
const SHOW_MODAL_DELETE = 'SHOW_MODAL_DELETE';
const DELETE = 'DELETE';
const CLOSE_MODAL_DELETE = 'CLOSE_MODAL_DELETE';
const GET_VALUE_ADD = 'GET_VALUE_ADD';
const GET_DATA = 'GET_DATA';
const RESET_VALUE_ADD = 'RESET_VALUE_ADD';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SAVE_BOOK_ID = 'SAVE_BOOK_ID';
export {
	SAVE_BOOK_ID,
	SET_CURRENT_PAGE,
	RESET_VALUE_ADD,
	GET_DATA,
	GET_VALUE_ADD,
	CHANGE_THEME,
	SEARCH,
	SHOW_MODAL_ADD,
	ADD,
	CLOSE_MODAL_ADD,
	SHOW_MODAL_DELETE,
	DELETE,
	CLOSE_MODAL_DELETE,
};
